// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MintFlipNFT$Type } from "./MintFlipNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MintFlipNFT"]: MintFlipNFT$Type;
    ["contracts/MintFlipNFT.sol:MintFlipNFT"]: MintFlipNFT$Type;
  }

  interface ContractTypesMap {
    ["MintFlipNFT"]: GetContractReturnType<MintFlipNFT$Type["abi"]>;
    ["contracts/MintFlipNFT.sol:MintFlipNFT"]: GetContractReturnType<MintFlipNFT$Type["abi"]>;
  }
}
